version: '3'

services:
  api:
    build:
      context: ./apigw
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - authservice
      - redis

  authservice:
    build:
      context: ./authservice
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"